### ISSUE TITLE
NFT Maker

### ISSUE THREAD

**Issue by mave99a** [ArcBlock/dappideas#142]
Eos 的voice 现在就变成一个NFT maker. 

https://www.voice.com

**Comment by mave99a** [comment]
https://sweatynft.com/

for generative

**Comment by mave99a** [comment]
https://www.buildship.dev/

**Comment by mave99a** [comment]
https://www.nameless.io/

**Comment by wangshijun** [comment]
### 产品形态

可以独立使用，也可以组合到其他 Blocklet 内使用

### 需求概述

- 能用其在 ocap 链上创建用户自己的 nft，自己的 nft-factory 等
- 能和其他产品功能组合起来，比如创建完立即起售卖，创建完转送给其他人等等

### 具体场景

- 比如和我们的 nft-marketplace 组合到一起，用户登录上去之后可以自己创建并出售 nft
- 比如和我们的 devcon 集成在一起，设计师登录上去创建 nft 直接颁给获奖者
- 比如和 dao 应用组合在一起，管理员登录上去给成员颁发徽章，比如员工周年纪念徽章

### 技术需求

- 创建 nft 需要指定 nft-display，nft-display 可以上传文件、svg、压缩包等，nft-display 应该托管在 s3 或者 ipfs 上面
- nft-maker 和其他模块等交互需要遵守标准的协议，比如列出某个人自创的 nft

更多待补充

**Comment by wangshijun** [comment]
@mave99a nft 创建者的在流转过程中应该得到分成还需要链的支持，这个在 kackweek 还搞不定

**Comment by mave99a** [comment]
分成可以慢慢来～ 先能有个普通用户就能用的builder 是一大进步

**Comment by wangshijun** [comment]
https://github.com/ArcBlock/dappideas/issues/202

**Comment by wangshijun** [comment]
related https://github.com/ArcBlock/dappideas/issues/75

我们可以把 Token Builder 和 NFT Maker 分成两个 Blocklet。

**Comment by mave99a** [comment]
成为了我们的一个产品
