### ISSUE TITLE
HackWeek 202204 计划

### ISSUE THREAD

**Issue by wangshijun** [ArcBlock/dappideas#202]
一个持续完善的hackweek流程文档：
https://www.notion.so/arcblock/Hackweek-69e9aa2abd34400ab8809b42eccdf595 

## 时间安排

4月2日讨论、确定选题，然后启动，4月8日 Demo 和评奖

## 奖项设置

Demo 环节会评选出 5 个 Demo，每个优胜奖会有 1000 $ABT 的奖金。

## 活动规则

- 所有的工程师都可以参与，如果需要设计资源需自行协调，原则上每位工程师负责 1 个项目，不建议以团队形式参与
- 项目选题只能是 Blocklet，重点是构建出高质量的小应用，或可被组合使用的组件，原则上不建议在现有产品上构建新功能
- 最终 Demo 的项目要实用、完整，而不应该是概念，甚至是个 Mock，建议选题尽量小，哪怕是 1 个项目的第一阶段
- 对于比较熟悉 Blocklet 开发的工程师，可以选择比较实用的 Blocklet，这些 Blocklet 活动后会成为我们的正式产品
- 对于不太熟悉 Blocklet 开发的工程师，可以选择实现简单的 Demo，也可以考虑把某些有实用价值的开源项目包装转换成 Blocklet

## 选题范围

> 待补充

- NFT Maker  @LancelotLewis 
- DID Voting 
- DID Survey（Form Builder + Collector + Token Reward on Submit）
- DID Authenticator（Unlock、Add with DID Wallet、Backup to DID Storage）
- DID Linklist
- Meilesearch Blocklet

## 本次的一个优先选题考虑

本次优先考虑至少实现3～4个和个人网站相关的blocklet，目标是这些blocklet 最终能组合成为非常棒的个人网站。 

参考这个Slides 中关于个人网站的结构解破：
https://arcblock.slack.com/archives/CAFT3TJ1Y/p1648782338357739

**Comment by mave99a** [comment]
可组合的功能单一但完善的blocklet 优先于完整功能但不具有组合用途的。 

通过日积月累形成一系列可组合的blocklet 更符合长期策略。

**Comment by mave99a** [comment]
一个最简单基础的内容工具，如blog，twitter，bbs 这样的其实在很多场合都有其价值。 我们需要这样一个基础内容部件

**Comment by wangshijun** [comment]
https://github.com/blocklet/hackweek-202204/blob/main/README.md
