### ISSUE TITLE
NFT交易与展示一体化平台

### ISSUE THREAD

**Issue by k1ic** [ArcBlock/dappideas#62]
目前NFT领域加密艺术品市场很活跃，但多是交易与展示分离，如：opensea、superrare、knownorigin等为单纯交易平台，decentraland、cryptovoxels为纯展示平台，若能将合二为一，必定是1+1>2

**Comment by mave99a** [comment]
opensea 可以把交易展示用iframe嵌入在外部的做法挺好的。

**Comment by mave99a** [comment]
https://microsoft.enjinx.io/eth/platform/3368/assets

可参考微软这个 NFT 浏览器的设计，挺简洁明了的

<img width="909" alt="image" src="https://user-images.githubusercontent.com/41923/85487370-4a4a1880-b581-11ea-8758-74b02f5b8a1c.png">

**Comment by mave99a** [comment]
https://enjinx.io/eth/marketplace

<img width="655" alt="image" src="https://user-images.githubusercontent.com/41923/85487736-03a8ee00-b582-11ea-9e8e-2b061822763f.png">

他们自带了交易市场

**Comment by k1ic** [comment]
> https://microsoft.enjinx.io/eth/platform/3368/assets
> 
> 可参考微软这个 NFT 浏览器的设计，挺简洁明了的
> 
> <img alt="image" width="909" src="https://user-images.githubusercontent.com/41923/85487370-4a4a1880-b581-11ea-8758-74b02f5b8a1c.png">

这个设计挺简洁的，opensea移动端ui有点丑
